### ISSUE TITLE
Facebook connect issue

### ISSUE THREAD

**Issue by asasnsba** [daye10/dokkan-battle-farm-bot-app#1]
I recently tried to log in and link a facebook account on the bot but it said I needed to download an app from the microsoft store which was not there. I dont know if this is a bot problem or fixable personal device problem.

**Comment by daye10** [comment]
juste close the browser and the connection will process, you dont have to dl any app 👍

**Comment by asasnsba** [comment]
Your welcome, ill attach an image to help clarify the problem if needed. 
![Desktop Screenshot 2022 09 10 - 17 48 18 65](https://user-images.githubusercontent.com/76786327/189502883-03439dca-5478-463e-9114-436d8271e2fb.png)

**Comment by daye10** [comment]
once you have clicked on "Continue" close the browser window, the link to your facebook account will process as well
