### ISSUE TITLE
Dokkan battle Alpha 

### ISSUE THREAD

**Issue by kazutoraz** [daye10/dokkan-battle-farm-bot-app#13]
hi brother i have a little problem when i try to create an android account it says captcha could not loaded do you have a solution?

**Comment by daye10** [comment]
Yeah it’s because of the 5.8.1 update, should be easy to fix, unfortunately I went on vacation and I didn’t bring my computer so I can’t fix it until the next 2-3 weeks

**Comment by kazutoraz** [comment]
No problem it's already nice to put your work at the service of everyone

**Comment by daye10** [comment]
fixed :)
