### ISSUE TITLE
TypeError on "zstages" command

### ISSUE THREAD

**Issue by mariuscontoli** [daye10/dokkan-battle-farm-bot-app#3]
Steps to reproduce :
- Type "zstages" command
- Select any stage on the GUI with any configuration

Behavior : TypeError('can only concatenate str (not "dict") to str')

**Comment by daye10** [comment]
yea sorry... I had to take care of it this week... but with school and life's unexpected events I haven't had much time these last few days for my personal projects, as soon as I have some time I'll get to it

**Comment by daye10** [comment]
Closing since https://github.com/daye10/dokkan-battle-farm-bot-app/issues/2 reporting the same issue,  it look like it's bc you have to unlock z battles on new accounts first, we actually working on it thanks

**Comment by mariuscontoli** [comment]
No prob! thanks
